export type Status = 'discovered'|'active'|'closing_soon'|'registration_closed'|'completed'|'cancelled'|'archived'|'needs_review';
export interface Opportunity {
 id:string;slug:string;title:string;summary:string;description:string;organizer_id:string|null;organizer_name:string;category:string;topics:string[];country:string;city:string;venue:string;latitude:number|null;longitude:number|null;is_online:boolean;is_hybrid:boolean;start_at:string|null;end_at:string|null;registration_deadline:string|null;registration_url:string|null;price_amount:number|null;currency:string;is_free:boolean;student_eligible:boolean;professional_eligible:boolean;experience_level:string;team_required:boolean;status:Status;confidence_score:number;fingerprint:string|null;is_demo:boolean;first_seen_at:string;last_verified_at:string|null;last_checked_at:string|null;created_at:string;updated_at:string;
}
export interface Profile {id:string;name:string;role:string;field:string;city:string;country:string;onboarded:boolean;created_at:string;updated_at:string}
export interface Preferences {user_id:string;experience_level:string;budget:string;budget_amount:number|null;currency:string;include_online:boolean;travel:boolean;interests:string[];categories:string[];weights:Record<string,number>}
export interface Organizer {id:string;name:string;slug:string;website:string|null;logo_url:string|null;description:string;country:string|null;city:string|null;verified:boolean;created_at:string}
export interface Source {id:string;name:string;domain:string;base_url:string;source_type:string;country:string|null;city:string|null;categories:string[];fetch_method:string;trust_score:number;is_official:boolean;refresh_interval_minutes:number;next_refresh_at:string;last_checked_at:string|null;last_success_at:string|null;last_changed_at:string|null;failure_count:number;active:boolean;etag:string|null;last_modified:string|null;content_hash:string|null;config:Record<string,unknown>;lease_until:string|null;lease_token:string|null;created_at:string}
export interface SourceEvidence {opportunity_id:string;source_id:string;source_url:string;source_name:string;source_domain:string;is_official:boolean;trust_score:number;checked_at:string}
export type ActionKind='interested'|'applied'|'going'|'not_interested'|'hide'|'hide_organizer';
