import type {Opportunity,Preferences,Profile} from "@/types/domain";
export const demoEnabled = () => process.env.RADAR_DEMO === "true" && process.env.VERCEL_ENV !== "production";
export const demoProfile:Profile={id:"demo",name:"Alex",role:"Student",field:"Computer Science",city:"Lahore",country:"PK",onboarded:true,created_at:"2026-09-01",updated_at:"2026-09-01"};
export const demoPreferences:Preferences={user_id:"demo",experience_level:"Beginner",budget:"mostly_free",budget_amount:null,currency:"PKR",include_online:true,travel:false,interests:["artificial-intelligence","programming","startups"],categories:["hackathons","workshops","networking"],weights:{}};
export function demoOpportunities():Opportunity[]{
 const now=Date.now(), date=(days:number)=>new Date(now+days*86400000).toISOString();
 const titles=["Lahore AI Hackathon","Developer Meetup Lahore","Startup Weekend Lahore","Cybersecurity Workshop","Student Entrepreneurship Challenge","Government Youth Technology Program"];
 return titles.map((title,i)=>({id:`00000000-0000-4000-8000-00000000000${i}`,slug:title.toLowerCase().replaceAll(" ","-"),title,summary:"A fictional opportunity for development preview only.",description:"This is fictional development data. It is not an actual opportunity and cannot accept applications.",organizer_id:null,organizer_name:["Lahore Builders Collective","Dev Community Lahore","Founders Studio"][i%3],category:["hackathons","developer-meetups","startup-events","workshops","competitions","government-programs"][i],topics:[["artificial-intelligence","programming"],["web-development","programming"],["startups","entrepreneurship"],["cybersecurity","programming"],["entrepreneurship"],["career-development"]][i],country:"PK",city:"Lahore",venue:i===3?"Online":"Lahore · Demo venue",latitude:null,longitude:null,is_online:i===3,is_hybrid:false,start_at:date(5+i*2),end_at:date(6+i*2),registration_deadline:date(1+i),registration_url:null,price_amount:0,currency:"PKR",is_free:true,student_eligible:true,professional_eligible:true,experience_level:i===3?"Intermediate":"Any",team_required:i===0,status:"active",confidence_score:0,fingerprint:null,is_demo:true,first_seen_at:date(-i),last_verified_at:null,last_checked_at:null,created_at:date(-i),updated_at:date(-i)}));
}
