import Link from "next/link";
import {notFound} from "next/navigation";
import {Shell} from "@/components/navigation/shell";
import {SaveButton} from "@/components/opportunities/save-button";
import {MatchBadge,DeadlineBadge} from "@/components/opportunities/card";
import {Chip} from "@/components/ui";
import {opportunity,savedIds,viewer} from "@/lib/data";
import {supabase,configured} from "@/lib/supabase/server";
import {demoEnabled,demoProfile,demoPreferences} from "@/lib/demo";
import {scoreOpportunity} from "@/lib/recommendations/score";
import {dateLabel} from "@/lib/utils/dates";
import type {SourceEvidence} from "@/types/domain";
export const dynamic="force-dynamic";
export default async function Detail({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const o=await opportunity(slug);if(!o)notFound();const saved=await savedIds([o.id]);let sources:SourceEvidence[]=[];let organizerSlug:string|undefined;
 if(configured()&&!demoEnabled()){const db=await supabase();const {data,error}=await db.from('opportunity_sources').select('*').eq('opportunity_id',o.id).limit(10);if(error)throw new Error(error.message);sources=data||[];if(o.organizer_id){const {data}=await db.from('organizers').select('slug').eq('id',o.organizer_id).maybeSingle();organizerSlug=data?.slug;}}
 let match=demoEnabled()?scoreOpportunity(o,demoProfile,demoPreferences):null;
 if(configured()&&!demoEnabled()){const db=await supabase();const {data:{user}}=await db.auth.getUser();if(user){const v=await viewer(false);match=scoreOpportunity(o,v.profile,v.preferences);}}
 return <Shell city={o.is_online?'Online':o.city}><Link className="back-link" href="/explore">← Back to opportunities</Link><div className="detail-grid"><article className="detail-main"><div className="tags"><Chip>{o.category.replaceAll('-',' ')}</Chip>{match&&<MatchBadge score={match.score}/>}</div><h1>{o.title}</h1><p className="muted">{organizerSlug?<Link href={'/organizer/'+organizerSlug}>{o.organizer_name} ↗</Link>:o.organizer_name} · {o.city}{o.is_online?' · Online':''}{o.is_hybrid?' · Hybrid':''}</p><section><h2>About this opportunity</h2><p className="prose">{o.description||o.summary}</p></section>{match&&<section><h2>Why Radar recommends this</h2><ul>{match.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></section>}<section><h2>Who can participate</h2><p>{o.student_eligible?'Students welcome. ':''}{o.professional_eligible?'Professionals welcome. ':''}{o.experience_level} experience. {o.team_required?'A team is required.':''}</p><div className="tags">{o.topics.map(t=><Chip key={t}>{t.replaceAll('-',' ')}</Chip>)}</div></section><section><h2>Venue</h2><p>{o.is_online?'Online':o.venue||'Venue to be announced'}{o.is_hybrid?' · Hybrid attendance available':''}</p></section><section><h2>Source information</h2><p className="muted">Last checked: {o.last_checked_at?dateLabel(o.last_checked_at):'Not yet checked'}<br/>Last verified: {o.last_verified_at?dateLabel(o.last_verified_at):'Not verified'}</p><p className="notice">Confirm current details on the official organizer website before applying.</p>{sources.map(s=><p key={s.source_id}><a href={s.source_url} target="_blank" rel="noopener noreferrer">{s.source_name} ↗</a>{s.is_official&&<Chip>Official source</Chip>}</p>)}{sources.length>1&&<Chip>Multiple sources</Chip>}</section></article><aside className="detail-side card"><DeadlineBadge value={o.registration_deadline}/><h2>{o.is_free?'Free to join':o.price_amount!==null?`${o.currency} ${o.price_amount}`:'Price not confirmed'}</h2><dl><dt>Starts</dt><dd>{dateLabel(o.start_at)}</dd><dt>Ends</dt><dd>{dateLabel(o.end_at)}</dd><dt>Apply before</dt><dd>{dateLabel(o.registration_deadline)}</dd><dt>Status</dt><dd>{o.status.replaceAll('_',' ')}</dd></dl>{o.registration_url&&!o.is_demo&&['active','closing_soon'].includes(o.status)?<a className="button" href={'/go/'+o.id}>Register / Apply ↗</a>:<p className="notice">{o.is_demo?'Fictional listing · Applications unavailable':'Registration is not currently available.'}</p>}{!o.is_demo&&<div className="save-detail"><SaveButton id={o.id} saved={saved.has(o.id)}/><span>Save for later</span></div>}<p className="muted small">Registration happens on the organizer’s website.</p></aside></div></Shell>;
}
